Feat/xd-109
amosproj/amos2024ss01-xcelerator-demo-app pull request #125
Opened 2024-06-03 21:46 UTC by Sabo2k

Similar to the [Prisma Documentation](https://www.prisma.io/blog/nestjs-prisma-error-handling-7D056s1kOop2), I've added an Exception Filter, which provides a more readable and user friendly error message for each HTTP request.

2024-06-05 11:57 UTC, KonsumGandalf requested changes

2024-06-05 11:57 UTC, KonsumGandalf commented on libs/cases/backend/case-management/src/lib/services/case.service.ts
> +					throw new NotFoundException('No Cases found.');
Why should this be an exception? When no case has been created yet, there should Error be thrown

2024-06-05 11:57 UTC, KonsumGandalf commented on libs/cases/backend/case-management/src/lib/services/case.service.ts
>  					overdue: Date.now() > new Date(item.dueDate).getTime(),
For sth like this `defaults` of `lodash` might be better, but it is **not** necessary to change it here, resolve this comment own your own.

2024-06-05 11:57 UTC, KonsumGandalf commented on libs/cases/backend/case-management/src/lib/services/case.service.ts
> +				throw new ConflictException('An error occurred while deleting the case.');
Pls be consitent with the Errors which are used. Why don't you use BadRequest Exception as well?

2024-06-05 11:57 UTC, KonsumGandalf commented on libs/cases/backend/case-management/src/lib/services/case.service.ts
> +					'Failed to create Case. Please check the provided data.',
```suggestion
					'Failed to create a case.',
```

The input is validated so it should be correct already

If you want to add 'real handling' you can directly print the console.log(caseData) in the next sentence

2024-06-05 11:57 UTC, KonsumGandalf commented on package.json
> +		"express": "^4.19.2",
I dont think you need to add this dependency. Pls try to do the statement `const response = context.getResponse<Response>();` without the type it should be automatically interfered. 
Add a large package just for a type seems to be an overhead to me.

If it is not possible *ignore this comment* and resolve it.

2024-06-05 11:57 UTC, KonsumGandalf commented on package.json
> +		"@types/express": "^4.17.21",
U dont even use the package.

2024-06-12 10:45 UTC, Sabo2k commented
![error-messagepng](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/63151233/b3c8ab49-8a68-4766-9b01-63d3ce53afc8)

2024-07-22 20:22 UTC, closed without merging