Feat/xd 110
amosproj/amos2024ss01-xcelerator-demo-app pull request #168
Opened 2024-06-13 08:49 UTC by Persists

2024-06-13 08:56 UTC, Persists commented
I know that there are still service tests missing, and the seeding may not be correct, using the enpoint

2024-06-14 15:48 UTC, KonsumGandalf requested changes
Great PR 2 small remarks

2024-06-14 15:48 UTC, KonsumGandalf commented on libs/common/backend/insight-hub/src/lib/services/iot-time-series.service.ts
> +	 * @param assetId The id of the asset asset
Maybe this is wrong

2024-06-14 15:48 UTC, KonsumGandalf commented on libs/common/backend/insight-hub/src/lib/services/users.service.ts
> +
why this line?

2024-06-14 15:49 UTC, Persists commented on libs/common/backend/insight-hub/src/lib/services/iot-time-series.service.ts
> +	 * @param assetId The id of the asset asset
true

2024-06-15 08:36 UTC, KonsumGandalf approved these changes
LGTM

2024-06-15 08:36 UTC, merged