feat: integrate swagger (XD-180)
amosproj/amos2024ss01-xcelerator-demo-app pull request #183
Opened 2024-06-16 15:26 UTC by KonsumGandalf

Closes: #180

2024-06-16 17:03 UTC, Persists requested changes

2024-06-16 17:03 UTC, Persists commented on libs/common/backend/swagger/README.md
Add a short description

2024-06-16 17:03 UTC, Persists commented on libs/facilities/backend/facilities/src/lib/controller/facilities.controller.ts
Add Api description for the facility endpoints?

2024-06-19 06:53 UTC, KonsumGandalf commented on libs/common/backend/swagger/README.md
Good point.

2024-06-19 06:56 UTC, KonsumGandalf commented on libs/facilities/backend/facilities/src/lib/controller/facilities.controller.ts
Oh damn forgot that :( Thank you.

2024-06-19 12:35 UTC, merged