Feat/xd 193
amosproj/amos2024ss01-xcelerator-demo-app pull request #199
Opened 2024-06-21 12:39 UTC by Persists

Connect cases to facility

2024-06-26 08:32 UTC, IngoSternberg commented on prisma/seed.ts
> +
So the #192 issue was also done on this branch, right?

2024-06-26 08:35 UTC, IngoSternberg commented on prisma/seed.ts
> +
Ah i see it was just moved below the newcaseData

2024-06-26 08:38 UTC, IngoSternberg commented on libs/cases/backend/case-management/src/lib/services/case.service.ts
> +						priority: priority as unknown as ECasePriority,
I have to say the  `type as unknown as ECaseType` but ther probably is no better way, right?

2024-06-26 08:38 UTC, Sungonogi commented on libs/cases/frontend/view/src/lib/components/case-browse/case-browse.component.ts
I am not sure what you changed here

2024-06-26 08:39 UTC, Sungonogi commented on libs/cases/frontend/view/src/lib/components/create-case/create-case.component.ts
also unsure what you changed apart from formatting

2024-06-26 08:39 UTC, IngoSternberg commented on libs/cases/frontend/view/src/lib/components/open-cases/open-cases.component.ts
since you moved the ICaseResponse. Was there an error linting so you had to move it to fix it?

2024-06-26 08:41 UTC, IngoSternberg commented on libs/facilities/backend/facilities/src/lib/controller/facilities.controller.spec.ts
In this file and also in some other files the spaces in brackets `[ abc ]` were removed `[abc]`. Could you run `nx run-many -t lint --fix` to fix it?

2024-06-26 08:46 UTC, IngoSternberg requested changes
Nice PR. I found some small things and have 2 questions. Also I have to say I don't really know that much about the backend.

I still have 2 general questions:
Is there now an attribute "amount of cases" or something for every facility or does that belong to another issue?
In the frontend cases stuff there are a lot of lines changed but I did not really see much of a difference. Did you do any bigger changes or only some formatting there?

2024-06-26 09:52 UTC, Persists commented on libs/cases/frontend/view/src/lib/components/case-browse/case-browse.component.ts
Nothing actually seems like just formatting, and the import, the case type import was wrong before

2024-06-26 09:53 UTC, Persists commented on libs/cases/frontend/view/src/lib/components/create-case/create-case.component.ts
Case import was wrong before it was from @frontend/...

2024-06-26 09:54 UTC, Persists commented on libs/cases/frontend/view/src/lib/components/open-cases/open-cases.component.ts
I guess, or my formatter is wrong

2024-06-26 09:55 UTC, Persists commented on libs/cases/frontend/view/src/lib/components/open-cases/open-cases.component.ts
I guess, or my formatter is wrongq

2024-06-26 09:56 UTC, Persists commented on libs/facilities/backend/facilities/src/lib/controller/facilities.controller.spec.ts
Yeah I can try, but I think I already run that, and this doesn't get fixed by that

2024-06-26 11:30 UTC, IngoSternberg commented on libs/cases/frontend/view/src/lib/components/case-browse/case-browse.component.ts
ok I guess when rebasing you can just pick the file from develop and then maybe check the import

2024-06-26 11:30 UTC, IngoSternberg commented on libs/cases/frontend/view/src/lib/components/create-case/create-case.component.ts
Ah okay

2024-06-26 11:32 UTC, IngoSternberg commented on libs/facilities/backend/facilities/src/lib/controller/facilities.controller.spec.ts
Okay that is unfortunate. If it actually does not work then the formatting is not super important I guess

2024-06-26 11:33 UTC, IngoSternberg commented on libs/cases/frontend/view/src/lib/components/open-cases/open-cases.component.ts
see the facilities.controller.spec.ts

2024-07-04 22:51 UTC, IngoSternberg commented
Since you asked if the frontend works I tested it and it seemed ok. The state management from the current develop branch is not yet here but since it doesn't affect the changed files it should be ok.

2024-07-04 22:54 UTC, IngoSternberg approved these changes
LGTM!

There are some files that were not really changed and don't really need to be in this PR but considering how annoying rebasing is I think you handled the conflicts and everything pretty well

2024-07-04 23:04 UTC, merged