Feat/xd-153
amosproj/amos2024ss01-xcelerator-demo-app pull request #203
Opened 2024-06-24 17:16 UTC by Sabo2k

2024-06-24 17:22 UTC, IngoSternberg commented
The #153 issue is not "add filter options for the cases page" but something else. Did you pick the wrong name?

2024-06-24 17:28 UTC, Sabo2k commented
> The #153 issue is not "add filter options for the cases page" but something else. Did you pick the wrong name?

Yes, you're right. My bad. Thanks for letting me know 👍

2024-06-26 18:32 UTC, IngoSternberg commented on libs/cases/frontend/view/src/lib/components/create-case/create-case.component.html
> +                hide-list-header="true"
If I see it correctly that hide-list-header removes the "Please select an option" showing at the top of the selection
![grafik](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/375f850e-cd8d-4edd-9ca2-031deecee6bb)

If you don't like it we can definitely remove it but you should also do it for the other  2 \<ix-select\> then

2024-06-26 18:35 UTC, Sungonogi commented
I have to say in my opinion these HTML comments like \<!-- Date Selection- -\> are not very useful, because most of the time HTML code is self explanatory (and we don't have them anywhere else). But since they might be helpful in some cases it would be ok for me if you keep them.

2024-06-26 18:35 UTC, IngoSternberg requested changes
Only thing I found was the hide-list-header. Apart from that it looks good.

2024-07-02 17:11 UTC, IngoSternberg approved these changes

2024-07-02 17:11 UTC, IngoSternberg commented on libs/cases/frontend/view/src/lib/components/create-case/create-case.component.html
> +                hide-list-header="true"
Ty for removing it

2024-07-11 21:09 UTC, IngoSternberg commented
There are so many files changed eventhough you only changed one. Sometimes this happens eventhough there is no difference to develop, but here there is a [difference](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/compare/develop...feat/xd-153). Since you only changed one file I suggest that you copy that somewhere then completely reset this branch or create a new branch of develop. Then paste that file on the reseted/new branch and merge that

2024-07-13 08:49 UTC, closed without merging