Feat/xd 54
amosproj/amos2024ss01-xcelerator-demo-app pull request #87
Opened 2024-05-21 20:46 UTC by IngoSternberg

merge detail page into develop so we can show it in the meeting tomorrow

2024-05-21 20:52 UTC, IngoSternberg commented
The test is not working because of the "import * as echarts from 'echarts/core';" in the detail.page.ts.
This is how they do it in the siemens ix [docu](https://ix.siemens.io/docs/controls/charts/) so I don't see a way to fix it for now. We might have to disable this check in jest

2024-05-21 22:28 UTC, PatrickSchm1dt commented on libs/facilities/frontend/view/src/lib/components/detail/detail.page.html
TODO: Add show work orders card and a button to create work orders page.
But can be done in a seperate Issue

2024-05-21 22:32 UTC, PatrickSchm1dt requested changes
The tests have to be green before merging, so please fix the import or adjust the test for this special import.

2024-05-22 05:49 UTC, IngoSternberg commented on libs/facilities/frontend/view/src/lib/components/detail/detail.page.html
Actually this card and button is already there. Since we don't have real work orders so far it does not show anything useful tho

2024-05-22 05:53 UTC, IngoSternberg commented
I know. The problem is that if I remove that part  the chart looks ugly because then it is not the Siemens Theme. The only way I know how fix it is probably to remove the test for now

2024-05-22 10:11 UTC, IngoSternberg commented
nice that you managed to fix it @PatrickSchm1dt

2024-05-22 10:12 UTC, HaruspexSan approved these changes
review look good, thanks for making the imports look better in many files.

2024-05-22 10:13 UTC, PatrickSchm1dt approved these changes

2024-05-22 10:14 UTC, merged